services:
  db:
    image: postgres:13
    container_name: playbook-insights-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: playbook_insights_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:5080/api
    container_name: playbook-insights
    ports:
      - "5080:5080"
    environment:
      PLAYER_DATABASE_URL: postgresql://myuser:mypassword@db:5432/playbook_insights_player_db
      TEAM_DATABASE_URL: postgresql://myuser:mypassword@db:5432/playbook_insights_team_db
      DB_SERVER_HOSTNAME: db
      DB_SERVER_PORT: 5432
      DB_SERVER_USERNAME: myuser
      DB_SERVER_PASSWORD: mypassword
      TEAM_DB_NAME: playbook_insights_team_db
      PLAYER_DB_NAME: playbook_insights_player_db
      API_PORT: 3000
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  postgres-data: