version: '3.8'

services:
  nginx:
    container_name: Playbook_Insights_Proxy
    image: nginx:alpine
    ports:
      - "5080:80"  # Only expose one external port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
    depends_on:
      - api
    networks:
      - app_network

  # frontend:
  #   container_name: Playbook_Insights_Frontend
  #   build:
  #     context: ./Frontend
  #   networks:
  #     - app_network

  api:
    container_name: Playbook_Insights_API
    build:
      context: ./API
    ports:
      - "3000:3000"  # Expose API port
    networks:
      - app_network


  # aggregator:
  #   container_name: Playbook_Insights_Aggregator
  #   build:
  #     context: ./Aggregator
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge
